[tool.poetry]
name = "BKE-template"
version = "0.1.0"
description = ""
authors = ["marijnkneppers@gmail.com"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"
replit = "^3.2.4"
matplotlib = "^3.5.3"
jsons = "^1.6.3"
start = "^0.2"
end = "^1.3.1"

[tool.poetry.dev-dependencies]
debugpy = "^1.6.2"
python-lsp-server = {extras = ["yapf", "rope", "pyflakes"], version = "^1.5.0"}
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
